# Generated by Django 2.1.4 on 2019-01-02 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('NA', 'Native Speaker'), ('BG', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lang_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lang_1_proficiency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lang_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lang_2_proficiency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lang_3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lang_3_proficiency',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_entries_corrected',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
