# Generated by Django 2.1.4 on 2018-12-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lang_2',
            field=models.CharField(blank=True, choices=[('FR', 'French'), ('EN', 'English'), ('JA', 'Japanese')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang_2_proficiency',
            field=models.CharField(blank=True, choices=[('NA', 'Native Speaker'), ('BG', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang_3',
            field=models.CharField(blank=True, choices=[('FR', 'French'), ('EN', 'English'), ('JA', 'Japanese')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang_3_proficiency',
            field=models.CharField(blank=True, choices=[('NA', 'Native Speaker'), ('BG', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_entries_corrected',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
