# Generated by Django 2.1.4 on 2019-01-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='language',
            field=models.ForeignKey(default='French', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='language.Language'),
            preserve_default=False,
        ),
    ]
